config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :challenges
  root to: "challenges#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :challenges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!

  def index
    @challenges = current_user.challenges
  end

  def show
    @challenge = current_user.challenges.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_challenge.html.erb
<li>
  <%= link_to challenge.name, challenge_path(challenge) %>
</li>

app/views/challenges/index.html.erb
<ul id="challengs">
  <%= render @challenges %>
</ul>

app/views/challenges/show.html.erb
<h1><%= @challenge.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>